// Generated by slidecraft — extract-pptx-theme.py
import { defineConfig } from 'unocss'
export default defineConfig({
  theme: { colors: {
      'textprimary': '#1D1D1F',
      'bgprimary': '#FFFFFF',
      'textsecondary': '#0BF000',
      'bgsecondary': '#C2C2C8',
      'accent1': '#E0E0E3',
      'accent2': '#55FF4D',
      'accent3': '#575E62',
      'accent4': '#C2C2C8',
      'accent5': '#90FF8B',
      'accent6': '#AAAEB0',
      'link': '#575E62',
      'linkvisited': '#575E62',
  }, },
})
